#! /usr/bin/env ruby

activerecord_uml = File.join __dir__,"../lib/activerecord_uml"
ruby_script = "require \"#{activerecord_uml}\"; ActiverecordUml.draw"
rails = File.join Dir.pwd,"bin/rails"
rails_runner_command = "echo '#{ruby_script}' | #{rails} runner - #{ARGV.join ' '}"

system rails_runner_command